# This file contains values from Cookiecutter

default_context:
  project_name: "datafirst"
  project_description: "Awesome `datafirst` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "ckids-datafirst"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "ckids_datafirst"
  email: "mosorio@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
